---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by WangXinchao.
--- DateTime: 2025-10-03 11:12:07
---

-- 需要判断秒杀优惠券的库存是否充足，要传入一个优惠券的id

local voucherId = ARGV[1]
local userId = ARGV[2]
local orderId = ARGV[3]

local stockKey = "seckill:stock:" .. voucherId;
local orderKey = "seckill:order:" .. voucherId;

-- 判断库存是否充足
-- 获取库存
local stock = tonumber(redis.call("get", stockKey))
if (stock <= 0) then
    return 1; -- 库存不足，返回1
end
-- 判断用户是否下单
local ordered = redis.call("sismember", orderKey, userId)
if (ordered == 1) then
    return 2; -- 重复下单
end

-- 可以下单，扣减库存，添加set
redis.call("incrby", stockKey, -1);

redis.call("sadd", orderKey, userId);

-- 发送消息到队列: stream.orders, XADD stream.orders * k1 v1 k2 v2 ...

redis.call("xadd", "stream.orders", "*",
        "userId", userId,"voucherId", voucherId, "id", orderId);

return 0;
